name: TerrariaReinforce
version: @version@
main: pw.illusion.reinforce.Reinforce
depend: [Illusion.Core,Vault]
api-version: 1.13
commands:
  trf:
    description: TerrariaReinforce main cmd
    permission: trf.use
    usage: /trf