name: TerrariaReinforce
version: @version@
main: pw.illusion.reinforce.Reinforce
depend: [Vault,LangUtils]
api-version: 1.13
commands:
  trf:
    description: TerrariaReinforce main cmd
    usage: /trf